### ISSUE TITLE
cookie problem

### ISSUE THREAD

**Issue by dexter101010** [P4ntruka/cloud-academy-dl#2]
Hi, 

When i am trying to download some course, i get this error : 

E:\Cloud>python cloud.py
Loading cookie from file cookie.txt
Could not read cookie! Exiting...

I did create the cookie file like it is writen in readme.

Thanks!

**Comment by P4ntruka** [comment]
Hi

Please, can you show more details of how you are running it? specifying the url of the course and the format of your cookies.txt file.

Regards.

**Comment by dexter101010** [comment]
Hi man, 


Thanks for your reply.

E:\Cloud>python cloud-academy-dl.py --cookie=cookie.txt https://cloudacademy.com/course/advanced-vm-management-in-azure-1020/demo-implementing-a-vm-scale-set-with-autoscaling/?context_id=389&context_resource=lp
Traceback (most recent call last):
  File "cloud-academy-dl.py", line 182, in <module>
    main()
  File "cloud-academy-dl.py", line 179, in main
    get_course_contents(course_url, parse_cookie_file(cookiefile), output_dir, video_res)
  File "cloud-academy-dl.py", line 162, in parse_cookie_file
    auth_cookies = {'authorization': auth[0], 'cookie': cookies[0]}
IndexError: list index out of range
'context_resource' is not recognized as an internal or external command,
operable program or batch file.


This is how it looks my cookie file :

clouda-session=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx; csrftoken=U7kPBtu83eeql15v7qNgmmANiqFPwdEgS7UUbcMzgli6LfEEUkZIKXZF7xynDu4x; sessionid=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx; ca_jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImxhcnJpZXV4ZXJpY2tAZ21haWwuY29tIiwib3JpZ19pYXQiOjE1OTMzNDg1NDQsImZlYXR1cmVzIjpbXSwiY29ybl9jb21wYW55X2FjY291bnRfaWQiOm51bGwsImNvbXBhbnlfYWNjb3VudF9pZCI6bnVsbCwibWVtYmVyc2hpcF90aWVyIjoiaW5kaXZpZHVhbCIsInVzZXJfaWQiOjMyOTUwNSwiY3VzdG9tZXJfbGlmZWN5Y2xlIjoic3Vic2NyaXB0aW9uLWFjdGl2ZSIsInRlbmFudF9pZCI6ImNsb3VkYWNhZGVteSIsImNvbXBhbnlfYWNjb3VudF9kb2VzX2NyZWF0ZV9wdWJsaWNfY29udGVudCI6bnVsbCwiYWN0b3JfaWQiOiI1ZWM0ZDdlYWU5NDVlZjBiZjRhY2EyZmYiLCJleHAiOjE1OTMzNDk3NDQsImVtYWlsIjoibGFycmlldXhlcmlja0BnbWFpbC5jb20ifQ.DNoM7jUN8Fnf7XHKAy67NQ1vhD0fHp_xxxxxxxxxxxx

**Comment by P4ntruka** [comment]
You cookie is wrong, you need to do this:

![cookie example](https://user-images.githubusercontent.com/36051334/85949355-42dd9300-b924-11ea-98e9-6f332f197f0d.jpeg)

and the url must be in double quotes:

python cloud-academy-dl.py --cookie=cookie.txt "https://cloudacademy.com/course/advanced-vm-management-in-azure-1020/demo-implementing-a-vm-scale-set-with-autoscaling/?context_id=389&context_resource=lp"

**Comment by dexter101010** [comment]
> You cookie is wrong, you need to do this:
> 
> ![cookie example](https://user-images.githubusercontent.com/36051334/85949355-42dd9300-b924-11ea-98e9-6f332f197f0d.jpeg)
> 
> and the url must be in double quotes:
> 
> python cloud-academy-dl.py --cookie=cookie.txt "https://cloudacademy.com/course/advanced-vm-management-in-azure-1020/demo-implementing-a-vm-scale-set-with-autoscaling/?context_id=389&context_resource=lp"

Hi man, 

You are right. I have tested and now iti is working. Thanks a lot :)

**Comment by P4ntruka** [comment]
> > You cookie is wrong, you need to do this:
> > ![cookie example](https://user-images.githubusercontent.com/36051334/85949355-42dd9300-b924-11ea-98e9-6f332f197f0d.jpeg)
> > and the url must be in double quotes:
> > python cloud-academy-dl.py --cookie=cookie.txt "https://cloudacademy.com/course/advanced-vm-management-in-azure-1020/demo-implementing-a-vm-scale-set-with-autoscaling/?context_id=389&context_resource=lp"
> 
> Hi man,
> 
> You are right. I have tested and now iti is working. Thanks a lot :)

Great, I'm going to close the incident.
